/**
 * AI Image Recognition
 *
 * Uses Anthropic Claude (claude-3-5-sonnet) vision to analyse a photo and
 * return an auto-generated title, description, and tags.
 *
 * The API key is read from localStorage so the admin can enter it once in the
 * Image Recognition page without hard-coding credentials.
 *
 * Anthropic API reference:
 * https://docs.anthropic.com/en/api/messages
 */

export interface AIRecognitionResult {
  title: string;
  description: string;
  tags: string[];
  /** True when the result was generated by AI, false when it is a fallback */
  aiGenerated: boolean;
}

const STORAGE_KEY = 'traveltelly_anthropic_key';

export function getStoredApiKey(): string {
  return localStorage.getItem(STORAGE_KEY) ?? '';
}

export function setStoredApiKey(key: string): void {
  localStorage.setItem(STORAGE_KEY, key);
}

/**
 * Convert a File to a base64 string (without the data-URL prefix)
 */
function fileToBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result as string;
      // Strip "data:<mime>;base64," prefix
      resolve(result.split(',')[1]);
    };
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
}

/**
 * Analyse the image with Claude vision and return structured metadata.
 *
 * @param file          The image file to analyse
 * @param locationHint  Optional city/country hint to enrich the prompt
 * @param apiKey        Anthropic API key (falls back to localStorage)
 */
export async function analyzeImageWithAI(
  file: File,
  locationHint?: { city?: string; country?: string },
  apiKey?: string
): Promise<AIRecognitionResult> {
  const key = apiKey ?? getStoredApiKey();

  if (!key) {
    return fallbackResult(file, locationHint);
  }

  try {
    const base64 = await fileToBase64(file);

    // Anthropic requires a supported media type
    const mediaType = normalizeMediaType(file.type);

    const locationContext = locationHint
      ? `The photo was taken in ${[locationHint.city, locationHint.country].filter(Boolean).join(', ')}.`
      : '';

    const userPrompt = `You are an expert travel photographer and stock photo editor.
Analyse the provided travel photo and return a JSON object with these exact keys:
- "title": A concise, vivid title (max 80 characters).${locationContext ? ' Include the location.' : ''}
- "description": A rich stock-photo description (2–4 sentences). Mention subject, mood, lighting, and composition.${locationContext ? ' ' + locationContext : ''}
- "tags": An array of 10–20 lowercase keyword strings suitable for stock photo search (include place names, subjects, colours, mood, activity).
Respond ONLY with the raw JSON object — no markdown, no code blocks, no extra text.`;

    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': key,
        'anthropic-version': '2023-06-01',
        // Required for browser-based requests (CORS)
        'anthropic-dangerous-direct-browser-calls': 'true',
      },
      body: JSON.stringify({
        model: 'claude-3-5-sonnet-20241022',
        max_tokens: 700,
        messages: [
          {
            role: 'user',
            content: [
              {
                type: 'image',
                source: {
                  type: 'base64',
                  media_type: mediaType,
                  data: base64,
                },
              },
              {
                type: 'text',
                text: userPrompt,
              },
            ],
          },
        ],
      }),
    });

    if (!response.ok) {
      const errText = await response.text();
      console.error('Anthropic API error:', response.status, errText);
      return fallbackResult(file, locationHint);
    }

    const json = await response.json();
    // Claude returns content as an array of blocks
    const textBlock = json.content?.find((b: { type: string }) => b.type === 'text');
    const rawContent: string = textBlock?.text ?? '';

    // Strip any accidental markdown fences
    const cleaned = rawContent
      .replace(/^```json\s*/i, '')
      .replace(/^```\s*/i, '')
      .replace(/```\s*$/, '')
      .trim();

    const parsed = JSON.parse(cleaned) as {
      title?: string;
      description?: string;
      tags?: string[];
    };

    return {
      title: parsed.title ?? buildFallbackTitle(file, locationHint),
      description: parsed.description ?? '',
      tags: Array.isArray(parsed.tags) ? parsed.tags : [],
      aiGenerated: true,
    };
  } catch (err) {
    console.error('AI image recognition failed:', err);
    return fallbackResult(file, locationHint);
  }
}

/**
 * Anthropic only accepts these four media types for images.
 */
function normalizeMediaType(
  mimeType: string
): 'image/jpeg' | 'image/png' | 'image/gif' | 'image/webp' {
  const map: Record<string, 'image/jpeg' | 'image/png' | 'image/gif' | 'image/webp'> = {
    'image/jpeg': 'image/jpeg',
    'image/jpg': 'image/jpeg',
    'image/png': 'image/png',
    'image/gif': 'image/gif',
    'image/webp': 'image/webp',
  };
  return map[mimeType.toLowerCase()] ?? 'image/jpeg';
}

function buildFallbackTitle(
  file: File,
  locationHint?: { city?: string; country?: string }
): string {
  const parts: string[] = [];
  const baseName = file.name
    .replace(/\.[^/.]+$/, '') // remove extension
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
  if (baseName) parts.push(baseName);
  if (locationHint?.city) parts.push(locationHint.city);
  if (locationHint?.country) parts.push(locationHint.country);
  return parts.join(' – ') || 'Travel Photo';
}

function fallbackResult(
  file: File,
  locationHint?: { city?: string; country?: string }
): AIRecognitionResult {
  const locationTags: string[] = [];
  if (locationHint?.city) locationTags.push(locationHint.city.toLowerCase());
  if (locationHint?.country) locationTags.push(locationHint.country.toLowerCase());

  return {
    title: buildFallbackTitle(file, locationHint),
    description: locationHint
      ? `Travel photo taken in ${[locationHint.city, locationHint.country].filter(Boolean).join(', ')}.`
      : 'Travel photo.',
    tags: ['travel', 'photography', ...locationTags],
    aiGenerated: false,
  };
}
