/**
 * AI Image Recognition
 *
 * Uses OpenAI GPT-4o Vision (or any OpenAI-compatible endpoint) to analyse
 * a photo and return an auto-generated title, description, and tags.
 *
 * The API key is read from localStorage so the admin can enter it once in the
 * Image Recognition page without hard-coding credentials.
 */

export interface AIRecognitionResult {
  title: string;
  description: string;
  tags: string[];
  /** True when the result was generated by AI, false when it is a fallback */
  aiGenerated: boolean;
}

const STORAGE_KEY = 'traveltelly_openai_key';

export function getStoredApiKey(): string {
  return localStorage.getItem(STORAGE_KEY) ?? '';
}

export function setStoredApiKey(key: string): void {
  localStorage.setItem(STORAGE_KEY, key);
}

/**
 * Convert a File to a base64 data-URL string
 */
function fileToBase64DataURL(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
}

/**
 * Analyse the image with GPT-4o vision and return structured metadata.
 *
 * @param file        The image file to analyse
 * @param locationHint  Optional city/country hint to enrich the prompt
 * @param apiKey      OpenAI API key (falls back to localStorage)
 */
export async function analyzeImageWithAI(
  file: File,
  locationHint?: { city?: string; country?: string },
  apiKey?: string
): Promise<AIRecognitionResult> {
  const key = apiKey ?? getStoredApiKey();

  if (!key) {
    return fallbackResult(file, locationHint);
  }

  try {
    const dataURL = await fileToBase64DataURL(file);
    // Strip the data-URL prefix so we send only the base64 payload
    const base64 = dataURL.split(',')[1];
    const mimeType = file.type || 'image/jpeg';

    const locationContext = locationHint
      ? `The photo was taken in ${[locationHint.city, locationHint.country].filter(Boolean).join(', ')}.`
      : '';

    const systemPrompt = `You are an expert travel photographer and stock photo editor.
Analyse the provided travel photo and return a JSON object with these exact keys:
- "title": A concise, vivid title (max 80 characters). ${locationContext ? 'Include the location.' : ''}
- "description": A rich stock-photo description (2–4 sentences). Mention subject, mood, lighting, and composition. ${locationContext}
- "tags": An array of 10–20 lowercase keyword strings suitable for stock photo search (include place names, subjects, colours, mood, activity).
Respond ONLY with the JSON object, no markdown code blocks.`;

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${key}`,
      },
      body: JSON.stringify({
        model: 'gpt-4o',
        max_tokens: 600,
        messages: [
          {
            role: 'user',
            content: [
              { type: 'text', text: systemPrompt },
              {
                type: 'image_url',
                image_url: {
                  url: `data:${mimeType};base64,${base64}`,
                  detail: 'low',
                },
              },
            ],
          },
        ],
      }),
    });

    if (!response.ok) {
      const errText = await response.text();
      console.error('OpenAI API error:', errText);
      return fallbackResult(file, locationHint);
    }

    const json = await response.json();
    const content: string = json.choices?.[0]?.message?.content ?? '';

    // Parse the JSON response
    const cleaned = content
      .replace(/^```json\s*/i, '')
      .replace(/^```\s*/i, '')
      .replace(/```\s*$/, '')
      .trim();

    const parsed = JSON.parse(cleaned) as {
      title?: string;
      description?: string;
      tags?: string[];
    };

    return {
      title: parsed.title ?? buildFallbackTitle(file, locationHint),
      description: parsed.description ?? '',
      tags: Array.isArray(parsed.tags) ? parsed.tags : [],
      aiGenerated: true,
    };
  } catch (err) {
    console.error('AI image recognition failed:', err);
    return fallbackResult(file, locationHint);
  }
}

function buildFallbackTitle(
  file: File,
  locationHint?: { city?: string; country?: string }
): string {
  const parts: string[] = [];
  const baseName = file.name
    .replace(/\.[^/.]+$/, '') // remove extension
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
  if (baseName) parts.push(baseName);
  if (locationHint?.city) parts.push(locationHint.city);
  if (locationHint?.country) parts.push(locationHint.country);
  return parts.join(' – ') || 'Travel Photo';
}

function fallbackResult(
  file: File,
  locationHint?: { city?: string; country?: string }
): AIRecognitionResult {
  const locationTags: string[] = [];
  if (locationHint?.city) locationTags.push(locationHint.city.toLowerCase());
  if (locationHint?.country) locationTags.push(locationHint.country.toLowerCase());

  return {
    title: buildFallbackTitle(file, locationHint),
    description: locationHint
      ? `Travel photo taken in ${[locationHint.city, locationHint.country].filter(Boolean).join(', ')}.`
      : 'Travel photo.',
    tags: ['travel', 'photography', ...locationTags],
    aiGenerated: false,
  };
}
